"""product_add_file_url_and_thumbnail

Revision ID: 58a6c3e8e8b2
Revises: a0afc4973ae5
Create Date: 2025-03-29 11:59:18.534137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a6c3e8e8b2'
down_revision: Union[str, None] = 'a0afc4973ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'order')
    # ### end Alembic commands ###
