"""add_topic_column_for_email_table

Revision ID: 9a8717f9a07a
Revises: 04047fe04fae
Create Date: 2025-04-20 08:49:38.724473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9a8717f9a07a'
down_revision: Union[str, None] = '04047fe04fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receivedemail', sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receivedemail', 'topic')
    # ### end Alembic commands ###
