"""product_add_file_url_and_thumbnail

Revision ID: a0afc4973ae5
Revises: 10a8b9eb724d
Create Date: 2025-03-29 11:55:24.559875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0afc4973ae5'
down_revision: Union[str, None] = '10a8b9eb724d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('userManualFileURL', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('catalogueFileURL', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('quicksheetFileURL', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('userManualCoverImageURL', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('catalogueCoverImageURL', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('quicksheetCoverImageURL', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'quicksheetCoverImageURL')
    op.drop_column('product', 'catalogueCoverImageURL')
    op.drop_column('product', 'userManualCoverImageURL')
    op.drop_column('product', 'quicksheetFileURL')
    op.drop_column('product', 'catalogueFileURL')
    op.drop_column('product', 'userManualFileURL')
    # ### end Alembic commands ###
